### ISSUE TITLE
chained add won't allow for account to be added - assertion error 

### ISSUE THREAD

**Issue by BewiggedSpoon** [tellor-io/telliot-feed-examples#125]
[poly test output.log](https://github.com/tellor-io/telliot-feed-examples/files/8055997/poly.test.output.log)

**Comment by oraclown** [comment]
Hey, I believe it's because you're putting "0x" in front of the private key. From your logs:
`chained add polytest 0x[redacted] 80001`

When it should be: `chained add politest [redacted_private_key] 80001`

**Comment by BewiggedSpoon** [comment]
Hi Oraclown, I tried with and without the 0x infront of my private key (the private key has this at the beginning be default. Istill get assetion error.
