### ISSUE TITLE
CLI support for GasPriceOracle query type

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feed-examples#228]
Need to be able to submit values for instances of the GasPriceOracle query type via the `telliot-feeds` CLI.
Related: [#59](https://github.com/tellor-io/dataSpecs/issues/59)

**Comment by tallywiesenberg** [comment]
GasPriceOracle tx submitted
chainId 1
timestamp 1659536688
https://rinkeby.etherscan.io/tx/0x9d9956a40814d5205100f07deb2688cc18a9ad22d37764db6a789fa9c5554e5e
