### ISSUE TITLE
Add CLI command for tipping

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feed-examples#43]
something like `telliot-examples tip --legacy-id 1 -a 2` to tip 2 TRB for price of ETH/USD
another: `telliot-examples tip -lid 59 --amount 42` to tip 42 TRB for the price of ETH/JPY

**Comment by oraclown** [comment]
maybe add in functionality to tip periodically on a schedule, like every 3 days at midnight UTC

**Comment by clamdad** [comment]
I'm wondering if this should go into the core CLI.
