### ISSUE TITLE
Problem with WSS Infura Endpoint

### ISSUE THREAD

**Issue by Spuddyminer** [tellor-io/telliot-feed-examples#7]
Following the instructions from the readme, I received the following error when using web socket Infura endpoint (rinkeby) in endpoints.yaml:

Could not connect to RPCEndpoint(chain_id=4, network='rinkeby', provider='Infura', url='wss://mainnet.infura.io/ws/v3/fe515a1efde34f4d932f2496c50b9479', explorer='https://rinkeby.etherscan.io')

When I put in the https endpoint, telliot worked as expected. Hope this helps!

**Comment by oraclown** [comment]
Thanks Spuddy, will investigate

**Comment by oraclown** [comment]
I believe this is because it's trying to connect to rinkeby, but you put in your mainnet infura endpoint ^

**Comment by clamdad** [comment]
Is there any way to detect this configuration error?

**Comment by oraclown** [comment]
Closing bc I think it's a configuration error. I've submitted using wss infura Rinkeby and mainnet endpoints
