### ISSUE TITLE
Reporter CLI should accept query tag instead of legacy ID

### ISSUE THREAD

**Issue by clamdad** [tellor-io/telliot-feed-examples#81]
Currently, the reporter CLI is only capable of choosing legacy IDs using the `-lid` flag.

A method is required to choose any query to report to (e.g. `SpotPrice`).

We now have a query catalog that tags each known query ID with a simple human-readable tag:
- [Query Catalog](https://github.com/tellor-io/dataSpecs/blob/main/catalog.md)

It is accessible in python  through `telliot_core.data.query_catalog`

To add this flexibility, the reporter should accept query tags from the catalog.

Example: 
- `-q uspce-legacy` for Legacy ID 41.
- `-q ohm-eth-spot` for OHM/ETH spot price

**Comment by oraclown** [comment]
Whoever gets to this first, make sure you don't allow continuous reporting for legacy id 41, since it's manual input.
