### ISSUE TITLE
stop invalid gas speed inputs e.g. "super-slow", "hi", etc.

### ISSUE THREAD

**Issue by tallywiesenberg** [tellor-io/telliot-feed-examples#83]
Proposing for next gas improvements PR, limiting CLI inputs for gas speed to the following:
* slow
* medium
* fast
OR
* an integer (manual user override of etherscan API)

**Comment by oraclown** [comment]
Closing, because Click type choices takes care of this. User is can only use the given choices:
```python
@click.option(
    "--gas-price-speed",
    "-gps",
    "gas_price_speed",
    help="gas price speed for eth gas station API",
    nargs=1,
    type=click.Choice(
        ["safeLow", "average", "fast", "fastest"],
        case_sensitive=True,
    ),
    default="fast",
)
```
